services:
  api:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - path: .env
        required: false
    environment:
      DATABASE_MODE: sqlite
      DATABASE_PATH: /data/local.db
      MIGRATIONS_DIR: /app/migrations
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - sqlite-data:/data
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "main:app",
        "--app-dir",
        "src",
        "--host",
        "0.0.0.0",
        "--port",
        "8001",
        "--reload",
      ]

volumes:
  sqlite-data:
