@baseUrl = http://127.0.0.1:8001
@userId = 9f8d5fe1-80af-4701-8786-e260cf4a59ae

### User template
GET {{baseUrl}}/users/template

### List users
GET {{baseUrl}}/users

### Create user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Jon Doe",
  "email": "jon.doe@example.com",
  "roleIds": ["STANDARD", "ADMIN"]
}

### Get user by id
GET {{baseUrl}}/users/{{userId}}

### Full update user
PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "Jonathan Doe",
  "email": "jonathan.doe@example.com",
  "roleIds": ["STANDARD"]
}

### Delete user
DELETE {{baseUrl}}/users/{{userId}}
